// <auto-generated />
using System;
using Frets.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frets.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frets.Core.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Frets.Core.Entities.Chord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("Frets.Core.Entities.LevelThreshold", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Level"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpRequired")
                        .HasColumnType("integer");

                    b.HasKey("Level");

                    b.ToTable("LevelThresholds");
                });

            modelBuilder.Entity("Frets.Core.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StatusChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("StatusChangedBy");

                    b.HasIndex("ArtistId", "TitleSlug")
                        .IsUnique();

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Frets.Core.Entities.SongVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tuning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("SongVersions");
                });

            modelBuilder.Entity("Frets.Core.Entities.SongVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteWeight")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SongId", "UserId")
                        .IsUnique();

                    b.ToTable("SongVotes");
                });

            modelBuilder.Entity("Frets.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Frets.Core.Entities.UserChordProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPracticed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MasteryLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChordId");

                    b.HasIndex("UserId", "ChordId")
                        .IsUnique();

                    b.ToTable("UserChordProgress");
                });

            modelBuilder.Entity("Frets.Core.Entities.VersionChordIndex", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChordId")
                        .HasColumnType("uuid");

                    b.HasKey("VersionId", "ChordId");

                    b.HasIndex("ChordId");

                    b.ToTable("VersionChordIndex");
                });

            modelBuilder.Entity("Frets.Core.Entities.VersionChords", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId")
                        .IsUnique();

                    b.ToTable("VersionChords");
                });

            modelBuilder.Entity("Frets.Core.Entities.VersionTab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId")
                        .IsUnique();

                    b.ToTable("VersionTabs");
                });

            modelBuilder.Entity("Frets.Core.Entities.XpEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("XpEvents");
                });

            modelBuilder.Entity("Frets.Core.Entities.Song", b =>
                {
                    b.HasOne("Frets.Core.Entities.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frets.Core.Entities.User", "Author")
                        .WithMany("Songs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frets.Core.Entities.User", "StatusChangedByUser")
                        .WithMany()
                        .HasForeignKey("StatusChangedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artist");

                    b.Navigation("Author");

                    b.Navigation("StatusChangedByUser");
                });

            modelBuilder.Entity("Frets.Core.Entities.SongVersion", b =>
                {
                    b.HasOne("Frets.Core.Entities.Song", "Song")
                        .WithMany("Versions")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Frets.Core.Entities.SongVote", b =>
                {
                    b.HasOne("Frets.Core.Entities.Song", "Song")
                        .WithMany("Votes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frets.Core.Entities.User", "User")
                        .WithMany("SongVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frets.Core.Entities.UserChordProgress", b =>
                {
                    b.HasOne("Frets.Core.Entities.Chord", "Chord")
                        .WithMany("UserChordProgress")
                        .HasForeignKey("ChordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frets.Core.Entities.User", "User")
                        .WithMany("ChordProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frets.Core.Entities.VersionChordIndex", b =>
                {
                    b.HasOne("Frets.Core.Entities.Chord", "Chord")
                        .WithMany("VersionChordIndex")
                        .HasForeignKey("ChordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frets.Core.Entities.SongVersion", "SongVersion")
                        .WithMany("ChordIndex")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chord");

                    b.Navigation("SongVersion");
                });

            modelBuilder.Entity("Frets.Core.Entities.VersionChords", b =>
                {
                    b.HasOne("Frets.Core.Entities.SongVersion", "SongVersion")
                        .WithOne("VersionChords")
                        .HasForeignKey("Frets.Core.Entities.VersionChords", "VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SongVersion");
                });

            modelBuilder.Entity("Frets.Core.Entities.VersionTab", b =>
                {
                    b.HasOne("Frets.Core.Entities.SongVersion", "SongVersion")
                        .WithOne("VersionTab")
                        .HasForeignKey("Frets.Core.Entities.VersionTab", "VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SongVersion");
                });

            modelBuilder.Entity("Frets.Core.Entities.XpEvent", b =>
                {
                    b.HasOne("Frets.Core.Entities.User", "User")
                        .WithMany("XpEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Frets.Core.Entities.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Frets.Core.Entities.Chord", b =>
                {
                    b.Navigation("UserChordProgress");

                    b.Navigation("VersionChordIndex");
                });

            modelBuilder.Entity("Frets.Core.Entities.Song", b =>
                {
                    b.Navigation("Versions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Frets.Core.Entities.SongVersion", b =>
                {
                    b.Navigation("ChordIndex");

                    b.Navigation("VersionChords");

                    b.Navigation("VersionTab");
                });

            modelBuilder.Entity("Frets.Core.Entities.User", b =>
                {
                    b.Navigation("ChordProgress");

                    b.Navigation("SongVotes");

                    b.Navigation("Songs");

                    b.Navigation("XpEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
